Sprint 5 - Profile and Settings
ClevertecFrontendLab/Lex-pineapple pull request #6
Opened 2024-03-24 21:16 UTC by Lex-pineapple

2024-03-24 21:18 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711315124/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711315124/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711315124/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711315124/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711315124/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711315124/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711315124/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711315124/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711315124/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711315124/settings-sider-pro_833x900.png)

2024-03-25 13:00 UTC, kvadratikk requested changes
в отзывах не отображаются фотки и нет сортировки по дате. также кнопка должна называться "развернуть все отзывы"
![image](https://github.com/ClevertecFrontendLab/Lex-pineapple/assets/78285127/184e601e-9aff-4b0c-b158-02dc62c06f14)

2024-03-25 19:22 UTC, byshlata requested changes
Замечания по коду

2024-03-25 19:22 UTC, byshlata commented on src/components/auth/signin-links.tsx
> +        return undefined;
return просто тоже вернет undefined

2024-03-25 19:22 UTC, byshlata commented on src/components/drawer/Drawer.scss
> +            border-radius: 24px 24px 0 0;
в переменные, как и gap, margin, padding

2024-03-25 19:22 UTC, byshlata commented on src/components/modals/calendar/exercise-modal.tsx
> +        if (modalType === 'SHOW' && props.isEmpty) return true;
'SHOW' и остальные подобные в переменные

2024-03-25 19:22 UTC, byshlata commented on src/components/modals/calendar/exercise-modal.tsx
> +            if (modalTypeDet) return 312;
цифры в константы

2024-03-25 19:22 UTC, byshlata commented on src/components/modals/result/error-modal.tsx
> +    return (
деструктуризацию сделай, чтобы не писать везде props

2024-03-25 19:22 UTC, byshlata commented on src/components/private/calendar/drawer/add-exercise-drawer.tsx
> +        //     height={screens.xs ? 'calc(100% - 86px)' : 'auto'}
?

2024-03-25 21:53 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 5.
Количество непройденных тестов: 0.
***
**buy-tariff-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711403596/buy-tariff-success_1440x900.png)
***
**default-profile-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711403596/default-profile-page_1440x900.png)
***
**default-settings-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711403596/default-settings-page_1440x900.png)
***
**feedbacks with photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711403596/feedbacks%20with%20photo_1440x900.png)
***
**modal-big-photo_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711403596/modal-big-photo_1440x900.png)
***
**profile-modal-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711403596/profile-modal-error_1440x900.png)
***
**profile-modal-success_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711403596/profile-modal-success_1440x900.png)
***
**settings-page-with-sider_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711403596/settings-page-with-sider_360x740.png)
***
**settings-pro-cards_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711403596/settings-pro-cards_360x740.png)
***
**settings-sider-pro_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Lex-pineapple/1711403596/settings-sider-pro_833x900.png)

2024-03-25 22:09 UTC, byshlata approved these changes

2024-03-26 18:24 UTC, merged